---
title: Challenges
---

Challenges will be graded based on the best four out of six individual grades.

The challenge workflow is:

1. The challenge is online at least 7 days before the next session.
2. Students start working on the challenge and making submissions on GitHub Classrooms.
3. The last submission is due before the start of the next session.

Late submissions will not be accepted!

Challenges will be graded following a 4-category scale:

---- -------------------------------------------------
✓+   exceptional, above and beyond what was expected
✓    completed with good effort
✓-   acceptable, but major deficiencies
∅    unacceptable; did not submit
---- -------------------------------------------------


# The challenges

| Assigned  | Due       | Coding Challenge                         |
| -         | -         | -                                        |
| Session 0 | Session 1 | [The Warm Up!](#challenge-0-the-warm-up) |
| Session 1 | Session 2 | The RMarkdown Project                    |
| Session 2 | Session 3 | TBA                                      |
| Session 4 | Session 5 | TBA                                      |
| Session 6 | Session 7 | TBA                                      |
| Session 8 | Session 9 | TBA                                      |


## Challenge 0: The Warm Up!

Challenge 0 will be completed together during the first session.
You can try to do this challenge, by yourself, before the first session. This will help you better understand some of the main tools we will use throughout the course.

### Instructions
0. Open RStudio.
1. Create a new RMarkdown document (a `.Rmd` file) in RStudio (icon with a white page and a green plus sign on the upper left corner).
2. Add a new title and author then click "OK". RStudio will create a default template page.
3. Compile the document by clicking the Knit button (the little blue wool ball). This will ask you how you want to name your output file and were were you want to save it. Once you validate, RStudio will generate an `.Rmd` and an `.html` file. Once the compilation is completed, it will display the rendered `html` page.
4. Accept the Challenge 0: [The Warm Up!](https://classroom.github.com/a/ZQr1J_Tz).
5. Upload the newly created R Markdown (`.Rmd`) and the newly generated HTML (`.html`) file to the github challenge repository.
6. Add a message to your commit (e.g. "My first submission!")

