---
title: "Session 1: Introduction"
subtitle: "Objectives:"
---

- Get familiar with the course structure
- Learn about open source tools
- Set up a computational working environment

# Resources

## Cheatsheets
- [RStudio](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf)
- [RMarkdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)

## Readings
- [RMarkdown](https://r4ds.had.co.nz/r-markdown.html#r-markdown)

## Practice
- [Markdown](https://commonmark.org/help/tutorial/)
- [RMarkdown](https://learn.datacamp.com/courses/reporting-with-rmarkdown)

# GitHub

### Hack Time!

Your first steps on GitHub:

1. Go to [www.github.com](https://github.com/) and identify your account name.
2. Share your [GitHub Account](https://github.com/) name with the class.
3. Create your first GitHub repository with a README.md file
    - Notice that `.md` files are Markdown files.
4. Edit the README file on GitHub.
    - Change the main title in the file.
    - Add a new sentence.
    - Add a bullet list with three items.
5. Make your first commit!
    - Don't forget to add a message to your commit

# RStudio

### Hack Time!

Your first lines of code:

1. Launch RStudio.
2. Create a new RMarkdown document (`.Rmd`).
3. Knit (render) the document as an HTML file.
    - The first time you run this, RStudio will ask you to install new functionalities and packages.
    - We need these functionalities so don't forget to accept when prompted!

Great! You just run your first coding script and created a web page!

Now let's try to create PDF files.

1. Locate the console pane in RStudio. It should be the bottom left pane in RStudio.
2. Copy the following command lines in the console and run them by hitting ENTER:
    ```{r eval=FALSE}
    install.packages('tinytex')
    tinytex::install_tinytex()
    ```

3. Now locate the small triangle right to the Knit button (top left pange) and choose Knit to PDF.
    - Again, the first time you do this it will download and install the functionalities required to create PDF files. It can take a couple minutes. A PDF will pop-up once the compilation successfully completed.

Great! You are now able to use markdown and the R language to make PDF files!

# Github and RStudio
Let's make them work together!

- Head to the [Challenges](challenges.html) page and complete the first challenge.


# Requirements

Make sure you have completed the [onboarding section](onboarding.html) prior to this session.

